axelarnetwork/axelar-contract-deployments

evm/deploy-const-address-deployer.js
evm/upgradable.js
evm/utils.js

PR for deployment script for constAddressDeployer using the CREATE opcode.

feat: deploy script for const address deployer

---

evm/index.js
evm/utils.js
index.js
info/testnet.json
package-lock.json
package.json

Polygon zkEVM uses [Poseidon](https://zkevm.polygon.technology/zkProver/poseidon-sm) hash function for it's state tree computation, which means code hash for contract bytecode isn't just `keccak256(bytecode)`. This affects our upgrade check.

feat: add polygon zk evm

---

evm/deploy-create3-deployer.js
evm/deploy-non-upgradable.js
evm/upgradable.js
evm/utils.js

PR for deployment script for InterchainGovernance, AxelarMultisigMintLimiter, and Operators. This script can easily be modified to deploy any non-upgradable contract using the create3 deployer.

feat: deployment script for governance, mint limiter, and operators

---

evm/deploy-contract.js
evm/deploy-create3-deployer.js
evm/deploy-non-upgradable.js
evm/deploy-upgradable.js
evm/upgradable.js
evm/utils.js

PR to deploy the create3 deployer contract on supported chains using the constAddressDeployer contract.

feat: deploy create3 deployer script

---

evm/deploy-const-address-deployer.js

- Verify if contract has already been deployed and exit earlier in such case
- Add `--force` flag to ignore the aforementioned check
- Ensure deployer account has funds

feat(scripts): small improvements to `deploy-const-address-deployer`

---

evm/deploy-contract.js

PR to add owner as a required constructor arg for Operators deployment.

fix: owner as constructor

---

evm/deploy-contract.js
info/mainnet.json
info/stagenet.json
info/testnet.json
package-lock.json
package.json

deployed from v5.1.1 with Create3Deployer as salt to `0x1a2Bf81BB73f7AC55CeE94d6216Bf62165586049` on all chains

feat: deployed create3deployer

---

info/testnet.json

RPC provided by centrifuge team [here](https://centrifuge.hackmd.io/kDjmVxlwQqySBb8qq9nuaA?view#Algol-Testnetwork)

feat: add centrifuge to info file

---

evm/README.md
evm/deploy-contract.js
evm/deploy-gateway-v4.3.x.js
evm/deploy-gateway-v5.0.x.js
evm/operators.js
evm/utils.js
package-lock.json
package.json

feat: v6 deployment improvements

---

evm/deploy-gateway-v5.0.x.js
evm/utils.js

[AXE-2058]
[AXE-2058]: https://axelarnetwork.atlassian.net/browse/AXE-2058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow deploying gateway implementation with create3

---

axelar-chains-config/info/testnet.json
evm/balances.js
evm/deploy-contract.js
evm/deploy-gateway-v5.0.x.js
evm/deploy-upgradable.js
evm/gateway.js
evm/governance.js
evm/multisig.js
evm/utils.js

[AXE-2058]
[AXE-2058]: https://axelarnetwork.atlassian.net/browse/AXE-2058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: testnet gateway upgrade [AXE-2058]

---

evm/verify-contract.js

[AXE-2166]
[AXE-2166]: https://axelarnetwork.atlassian.net/browse/AXE-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: support verification of IG and Multisig [AXE-2166]

---

axelar-chains-config/info/mainnet.json

[AXE-822]
[AXE-822]: https://axelarnetwork.atlassian.net/browse/AXE-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: onboard scroll mainnet

---

axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json
evm/deploy-contract.js
evm/deploy-gateway-v5.0.x.js
evm/gateway.js
evm/utils.js
evm/verify-contract.js

[AXE-2165]
[AXE-2165]: https://axelarnetwork.atlassian.net/browse/AXE-2165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: redeploy v5.4 Create3Deployer

---

evm/.example.keys.json
evm/README.md

Jira: https://axelarnetwork.atlassian.net/browse/AXE-1973

docs: for verification script [AXE-1973]

---

axelar-chains-config/info/mainnet.json

[AXE-2403]
[AXE-2403]: https://axelarnetwork.atlassian.net/browse/AXE-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: mainnet gateway upgrade

---

.prettierrc
axelar-chains-config/info/mainnet.json
evm/.example.keys.json

- Removes inconsistency between config file written by JSON.stringify and prettier

chore: use json stringify prettier format

---

evm/check-wallet-balance.js
evm/deploy-contract.js
evm/deploy-gateway-v6.2.x.js
evm/governance.js
evm/send-tokens.js
evm/sign-utils.js

- Fix nonce retrieval check
- Use static gas limit for offline signing
- Use 0 address when not changing the governance/mint limiter

fix: misc script fixes

---

.example.env
axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json
evm/README.md
evm/deploy-gateway-v6.2.x.js
package.json

Cleanup contract deployment instructions

chore: cleanup README

---

.github/workflows/test.yaml
evm/cli-utils.js
evm/deploy-its.js
evm/utils.js
evm/verify-contract.js
package-lock.json
package.json

Potential ITS deployment script refactor

feat: its deployment refactor

---

.github/workflows/test.yaml
evm/README.md
evm/governance.js

[AXE-2789]
[AXE-2789]: https://axelarnetwork.atlassian.net/browse/AXE-2789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: improve governance script

---

evm/README.md
evm/decode.js
evm/interchainTokenFactory.js
evm/its.js

Script to decode generic calldata and multicall specific calldata as per [AXE-2793](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2793)
[AXE-2793]: https://axelarnetwork.atlassian.net/browse/AXE-2793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Sample output for generic decode:
```
Contract name: InterchainTokenService
Decoded calldata: 
Function: deployInterchainToken
Arg names: salt, destinationChain, name, symbol, decimals, minter, gasValue
Arg values: 0x79d4bf58fff996a2ffaca4809382c4ddb24b53d6def5712c141e97a010f68178, Chain A, Token A, TKA, 18, 0x1234, 90
```
Sample output for decode multicall data:
```
Contract name: InterchainTokenService
Decoded calldata: 
Function: multicall
Decoded …
```

feat: decode calldata script

---

evm/its.js
evm/verify-contract.js

ITS post deploy checks for config values as per [AXE-2774](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2774)
[AXE-2774]: https://axelarnetwork.atlassian.net/browse/AXE-2774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: post deploy checks

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/testnet.json
evm/deploy-upgradable.js
evm/operators.js
evm/utils.js
package-lock.json
package.json

Upgrade gas service to `v6.2.1` and deploy Operators contract

feat: upgrade gas service and deploy operators

---

evm/sign-message.js

Add input validation checks for message and private key in `sign-message.js` script

refactor: add input validation checks in sign-message script

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/testnet.json

Add explorer names for chain configs

chore: add explorer names

---

.github/workflows/test.yaml
axelar-chains-config/info/mainnet.json
axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json
evm/chains.js
evm/deploy-contract.js
evm/deploy-gateway-v4.3.x.js
evm/deploy-gateway-v6.2.x.js
evm/deploy-its.js
evm/gateway.js
evm/governance.js
evm/its.js
evm/min-deposit-proposal.js
evm/verify-contract.js

Migrate from id to axelarId as per [AXE-2960](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2960)
[AXE-2960]: https://axelarnetwork.atlassian.net/browse/AXE-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: change chain.id to chain.axelarId

---

axelar-chains-config/info/testnet.json

https://axelarnetwork.atlassian.net/browse/AXE-3111

feat: add config for base sepolia

---

axelar-chains-config/info/testnet.json

https://axelarnetwork.atlassian.net/browse/AXE-3110

feat: add config for optimism sepolia

---

axelar-chains-config/info/mainnet.json

JIRA: https://axelarnetwork.atlassian.net/browse/AXE-3075

feat: add fraxtal config

---

axelar-chains-config/info/testnet.json

Add the id property in optimism-sepolia config

refactor: add id property in optimism-sepolia config

---

axelar-chains-config/info/testnet.json

https://axelarnetwork.atlassian.net/browse/AXE-3259

feat: add config for Blast Sepolia

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/testnet.json

Add config for Blast mainnet. Public rpc information is to be added when available.
Also updated the API for blast-sepolia testnet
https://axelarnetwork.atlassian.net/browse/AXE-3305

feat: add blast mainnet config

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/testnet.json
axelar-chains-config/package-lock.json
axelar-chains-config/package.json
evm/deploy-its.js
evm/its.js
evm/utils.js
package-lock.json
package.json

chore: upgrade ITS to v1.2.4

---

.github/workflows/lint.yaml
.github/workflows/test-chains-config.yaml
.github/workflows/test.yaml
package-lock.json
package.json

Add blacksmith to GitHub actions

feat: add blacksmith

---

evm/gas-service.js
evm/operators.js

feat(GasService): caching GMP fee results

---

axelar-chains-config/info/testnet.json
evm/gas-service.js
evm/operators.js
evm/utils.js
package-lock.json
package.json

feat(GasService): new structure for GasInfo

---

axelar-chains-config/info/devnet-amplifier.json
axelar-chains-config/info/devnet-verifiers.json
cosmwasm/deploy-contract.js

the change required for this: https://github.com/axelarnetwork/axelar-amplifier/pull/371
https://axelarnetwork.atlassian.net/browse/AXE-3837

feat: add msg id format to voting verifier instantiation msg

---

.github/workflows/update-gas-info.yaml
axelar-chains-config/info/testnet.json
evm/gas-service.js

chore: enable cron for testnet gas info updates

---

axelar-chains-config/info/testnet.json
evm/gas-service.js
evm/operators.js
evm/utils.js

ci(gas-info): handling timeout for Scroll

---

evm/utils.js

ci(gas-info): handling timeout for Filecoin

---

axelar-chains-config/info/testnet.json

https://axelarnetwork.atlassian.net/browse/AXE-3523

feat: add config for linea sepolia

---

axelar-chains-config/info/testnet.json

ci(gas-info): handling timeout for Linea and Mantle

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/testnet.json
package-lock.json
package.json
stellar/README.md
stellar/balances.js
stellar/cli-utils.js
stellar/generate-bindings.js
stellar/operators.js
stellar/utils.js

[AXE-3918]
Resource cost estimation script reference: https://gist.github.com/namankumar/2ebd9dd157b606c60c9bce3c580ea15b
Tx broadcast reference: https://developers.stellar.org/docs/smart-contracts/guides/transactions/invoke-contract-tx-js
[AXE-3918]: https://axelarnetwork.atlassian.net/browse/AXE-3918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): add stellar operators scripts

---

axelar-chains-config/info/testnet.json

ci(gas-info): increased Linea timeout

---

evm/cli-utils.js
evm/utils.js

I needed to do some fixes along the way when trying to deploy Amplifier contracts in our EVM chain. More to come as I go along with the deployment.

fix(evm): evm amplifier deployment fixes

---

evm/deploy-amplifier-gateway.js

For the salt derivation to be correct, this other PR needs to be merged: https://github.com/axelarnetwork/axelar-contract-deployments/pull/251
https://axelarnetwork.atlassian.net/browse/AXE-4153

fix(amplifier): salt derivation and chain.axelarId

---

axelar-chains-config/info/devnet-amplifier.json
axelar-chains-config/info/devnet-verifiers.json

https://axelarnetwork.atlassian.net/browse/AXE-4154

feat(amplifier): rename worker to verifier and update voting verifier source gateway address in jsons

---

axelar-chains-config/info/devnet-amplifier.json
axelar-chains-config/info/devnet-verifiers.json
cosmwasm/deploy-contract.js

https://axelarnetwork.atlassian.net/browse/AXE-4161

feat(amplifier): store domain separator when deploying MultisigProver

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/testnet.json
evm/deploy-upgradable.js
evm/utils.js

[AXE-4162]
[AXE-4162]: https://axelarnetwork.atlassian.net/browse/AXE-4162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(evm): upgrade mainnet gas service to v6.3.1

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/testnet.json

feat(evm): onchainGasEstimate for L2s

---

evm/deploy-gateway-v6.2.x.js

https://axelarnetwork.atlassian.net/browse/AXE-4203

refactor: remove static gas param specified for transferring auth ownership

---

sui/README.md
sui/deploy-gateway.js
sui/deploy-test.js
sui/gateway.js
sui/sign-utils.js
sui/types-utils.js

[AXE-4202]
[AXE-4202]: https://axelarnetwork.atlassian.net/browse/AXE-4202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sui)!: add sui gateway call contract

---

sui/sign-utils.js

https://axelarnetwork.atlassian.net/browse/AXE-4133

feat: add utility function to sign txs

---

evm/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-4227

feat(amplifier): update verifier set query

---

axelar-chains-config/info/testnet.json

Update RPC because the old one fetches incorrect gas estimates.

chore: updated polygon sepolia rpc

---

evm/deploy-amplifier-gateway.js

https://axelarnetwork.atlassian.net/browse/AXE-4289

feat(amplifier): store initial verifier set id when deploying amplifier gateway

---

sui/utils.js

Output for the `currnet_verifier_set` query changed, this PR updates the code accordingly

fix(sui): correctly parse `current_verifier_set` query

---

common/cli-utils.js
cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js
stellar/balances.js
stellar/generate-bindings.js
stellar/operators.js
sui/utils/cli-utils.js

[AXE-4659](https://axelarnetwork.atlassian.net/browse/AXE-4659)
This PR replaces the hardcoded env option list with dynamically generated values based on the list of file names in the `axelar-chains-info/info` directory.
[AXE-4659]: https://axelarnetwork.atlassian.net/browse/AXE-4659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: convert hardcoded envs to dynamic values

---

common/cli-utils.js
cosmwasm/cli-utils.js
cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js
stellar/balances.js
stellar/deploy-contract.js
stellar/generate-bindings.js
stellar/operators.js
sui/utils/cli-utils.js

This PR removes the duplicated env options

chore: reuse addEnvOptions

---

.github/workflows/test-sui.yaml

This PR moves Sui file changes detection inside the job, allowing the workflow to be set as a required check.

chore: check relevant changes in job

---

.github/workflows/test-sui.yaml

This PR fixes the issue that the test-sui workflow doesn't skip if changes aren't relevant.

ci(sui): fix test-sui workflow

---

sui/deploy-contract.js
sui/gas-service.js
sui/gateway.js
sui/gmp.js
sui/operators.js
sui/tokens.js
sui/transfer-object.js
sui/utils/sign-utils.js

[AXE-4701](https://axelarnetwork.atlassian.net/browse/AXE-4701)
Centralizes digest printing within the broadcast function, removing redundancy from individual script files.
[AXE-4701]: https://axelarnetwork.atlassian.net/browse/AXE-4701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(sui): print digest internally

---

cosmwasm/README.md
cosmwasm/cli-utils.js
cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js

https://axelarnetwork.atlassian.net/browse/AXE-4760

refactor(amplifier)!: use subcommands for governance proposals

---

axelar-chains-config/info/devnet-amplifier.json

https://axelarnetwork.atlassian.net/browse/AXE-4900

chore(amplifier): update rewards codeId (v1.1)

---

sui/deploy-contract.js

https://axelarnetwork.atlassian.net/browse/AXE-5266
This PR adds error message when there're dependency packages need to be deployed before the given package.

chore(sui): improve error message for deployment

---

axelar-chains-config/info/devnet-amplifier.json

fix: post upgrade - config update

fix: post upgrade - config update

---

axelar-chains-config/info/devnet-amplifier.json

https://axelarnetwork.atlassian.net/browse/AXE-5687

feat(config): add flow to devnet-amplifier

---

stellar/README.md
stellar/deploy-contract.js
stellar/gateway.js
stellar/generate-bindings.js
stellar/operators.js
stellar/utils.js

[AXE-5775](https://axelarnetwork.atlassian.net/browse/AXE-5775)
[AXE-5775]: https://axelarnetwork.atlassian.net/browse/AXE-5775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): update stellar deployment and gateway scripts

---

axelar-chains-config/info/devnet-amplifier.json

- stellar-test2 deployment config update on devnet amplifier

feat: stellar-test2 deployment config update on devnet amplifier

---

sui/deploy-contract.js
sui/utils/cli-utils.js

https://axelarnetwork.atlassian.net/browse/AXE-6142
Print env from .env file for `sui/deploy-contract.js` script

chore: print env for deployment script

---

evm/deploy-amplifier-gateway.js
evm/gateway.js
evm/governance.js
evm/multisig.js
package-lock.json
package.json
stellar/gateway.js

[AXE-6300](https://axelarnetwork.atlassian.net/browse/AXE-6300)
[AXE-6300]: https://axelarnetwork.atlassian.net/browse/AXE-6300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(gateway): update signer hash to signers hash

---

stellar/README.md
stellar/deploy-contract.js
stellar/its.js

[AXE-6236](https://axelarnetwork.atlassian.net/browse/AXE-6236)
- Add an initial script for deploying ITS contract
- Add an its.js script that allows setting/removing trusted ITS addresses
- Update Stellar README with new commands and edit for readability
[AXE-6236]: https://axelarnetwork.atlassian.net/browse/AXE-6236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): add Stellar ITS deployment script

---

axelar-chains-config/info/devnet-amplifier.json

[AXE-6339](https://axelarnetwork.atlassian.net/browse/AXE-6339)
[AXE-6339]: https://axelarnetwork.atlassian.net/browse/AXE-6339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(stellar): remove unused devnet-test config for devnet-amplifier

---

sui/README.md

This PR refactors `sui/README.md` by focusing on improving the overall structure and ordering the deployment scripts based on their dependencies.

docs(sui): update sui instructions

---

stellar/README.md
stellar/faucet.js
stellar/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-6456

feat(stellar): script for requesting testnet funds

---

axelar-chains-config/info/devnet-amplifier.json
stellar/README.md
stellar/deploy-contract.js

[AXE-6550](https://axelarnetwork.atlassian.net/browse/AXE-6550)
[AXE-6550]: https://axelarnetwork.atlassian.net/browse/AXE-6550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(gas-service): update initialize func name and config

---

.github/workflows/test-evm.yaml
evm/deploy-its.js
evm/interchainTokenFactory.js
evm/its.js
package-lock.json
package.json

Update to the latest ITS commit

chore(evm): update ITS version

---

stellar/deploy-contract.js

[AXE-6692](https://axelarnetwork.atlassian.net/browse/AXE-6692)
[AXE-6692]: https://axelarnetwork.atlassian.net/browse/AXE-6692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stellar): store initialize args

---

stellar/deploy-contract.js

added owner to gas service and fixed wasm hash logging.

chore(stellar): add owner to gas service and fix wasm hash logging

---

sui/utils/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-6782

chore(sui): add more help text when sui version mismatch

---

stellar/deploy-contract.js

[AXE-6870](https://axelarnetwork.atlassian.net/browse/AXE-6870)
[AXE-6870]: https://axelarnetwork.atlassian.net/browse/AXE-6870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): add interchain token wasm hash for interchain token service

---

stellar/README.md
stellar/deploy-contract.js
stellar/its.js

[AXE-6883](https://axelarnetwork.atlassian.net/browse/AXE-6883)
[AXE-6883]: https://axelarnetwork.atlassian.net/browse/AXE-6883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(stellar): update ITS deployment script and trusted chain

---

sui/deploy-contract.js

[AXE-6813]
[AXE-6813]: https://axelarnetwork.atlassian.net/browse/AXE-6813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: capture all OwnerCaps properly

---

cosmwasm/update-code-id.js
cosmwasm/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-7073

feat(cosmwasm): add new script to update configured codeId with the one currently being used by the contract

---

cosmwasm/README.md
cosmwasm/deploy-contract.js
cosmwasm/utils.js

Needs to be merged after https://github.com/axelarnetwork/axelar-contract-deployments/pull/492
https://axelarnetwork.atlassian.net/browse/AXE-5158

feat(cosmwasm): add subcommand for migration through admin account

---

axelar-chains-config/info/devnet-amplifier.json
axelar-chains-config/info/mainnet.json
axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json
stellar/deploy-contract.js

[AXE-7165]
[AXE-7165]: https://axelarnetwork.atlassian.net/browse/AXE-7165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): add native token address to stellar ITS deployment

---

stellar/README.md
stellar/deploy-contract.js

[AXE-7267](https://axelarnetwork.atlassian.net/browse/AXE-7267)
[AXE-7267]: https://axelarnetwork.atlassian.net/browse/AXE-7267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add token manager deployment script

---

stellar/README.md
stellar/gateway.js
stellar/gmp.js
stellar/its.js
stellar/utils.js

[AXE-7257](https://axelarnetwork.atlassian.net/browse/AXE-7257)
The previous PR is outdated and causes too many code conflicts, so I've closed it: https://github.com/axelarnetwork/axelar-contract-deployments/pull/490
[AXE-7257]: https://axelarnetwork.atlassian.net/browse/AXE-7257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add its example scripts 

---

stellar/README.md
stellar/deploy-contract.js

[AXE-7282](https://axelarnetwork.atlassian.net/browse/AXE-7282)
[AXE-7282]: https://axelarnetwork.atlassian.net/browse/AXE-7282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): add bytecode download and deploying contracts

---

.github/workflows/test-sui.yaml
common/cli-utils.js
sui/deploy-contract.js
sui/gas-service.js
sui/gateway.js
sui/gmp.js
sui/its-example.js
sui/its.js
sui/multisig.js
sui/operators.js
sui/tokens.js
sui/transfer-object.js
sui/utils/sign-utils.js
sui/utils/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-7287
This PR added a confirmation prompt before submitting the tx. The confirmation can be skipped with `-y`, `--yes` or set `YES=true` in the `.env` file.

chore(sui): ask for confirmation before submitting txs

---

stellar/README.md
stellar/cli-utils.js
stellar/its.js
stellar/utils.js

[AXE-7375](https://axelarnetwork.atlassian.net/browse/AXE-7375)
[AXE-7375]: https://axelarnetwork.atlassian.net/browse/AXE-7375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add encoding stellar recipient address to bytes

---

stellar/README.md
stellar/gateway.js
stellar/its.js

[AXE-7374](https://axelarnetwork.atlassian.net/browse/AXE-7374)
[AXE-7374]: https://axelarnetwork.atlassian.net/browse/AXE-7374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: implement execute for stellar its and gateway

---

evm/gateway.js

[AXE-7478](https://axelarnetwork.atlassian.net/browse/AXE-7478)
[AXE-7478]: https://axelarnetwork.atlassian.net/browse/AXE-7478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(evm): added is contract call approved and is message approved cmd

---

stellar/README.md
stellar/its.js
stellar/utils.js

[AXE-7206](https://axelarnetwork.atlassian.net/browse/AXE-7206)
[AXE-7206]: https://axelarnetwork.atlassian.net/browse/AXE-7206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): make gas token and amount optional for its commands

---

stellar/deploy-contract.js

[AXE-7487](https://axelarnetwork.atlassian.net/browse/AXE-7487)
[AXE-7487]: https://axelarnetwork.atlassian.net/browse/AXE-7487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): make minimum rotation delay optional

---

axelar-chains-config/info/devnet-amplifier.json
axelar-chains-config/info/mainnet.json

[AXE-7490](https://axelarnetwork.atlassian.net/browse/AXE-7490)
[AXE-7490]: https://axelarnetwork.atlassian.net/browse/AXE-7490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(stellar): update stellar explorer to stellar expert

---

package-lock.json
package.json
sui/gas-service.js
sui/operators.js

[AXE-7514]
[AXE-7514]: https://axelarnetwork.atlassian.net/browse/AXE-7514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sui)!: make it so the gas service scripts use SUI

---

common/utils.js

[AXE-7518](https://axelarnetwork.atlassian.net/browse/AXE-7518)
[AXE-7518]: https://axelarnetwork.atlassian.net/browse/AXE-7518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stellar): add stellar its in get its edge contract

---

evm/interchainTokenFactory.js

[AXE-7546](https://axelarnetwork.atlassian.net/browse/AXE-7546)
[AXE-7546]: https://axelarnetwork.atlassian.net/browse/AXE-7546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(evm): remove original chain from deploy remote canonical interchain token

---

package-lock.json
package.json
sui/deploy-contract.js
sui/gas-service.js
sui/operators.js

This rename makes the role naming more consistent across contracts

feat(sui)!: renamed GasCollectorCap to OperatorCap everywhere

---

cosmwasm/submit-proposal.js

accompanies this PR: https://github.com/axelarnetwork/axelar-amplifier/pull/760

fix: use max uint bits instead of max uint

---

stellar/its.js

[AXE-7523](https://axelarnetwork.atlassian.net/browse/AXE-7523)
[AXE-7523]: https://axelarnetwork.atlassian.net/browse/AXE-7523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stellar): display token id for its commands

---

stellar/README.md
stellar/gmp.js
stellar/its.js
stellar/operators.js
stellar/utils.js

[AXE-7648](https://axelarnetwork.atlassian.net/browse/AXE-7648)
[AXE-7648]: https://axelarnetwork.atlassian.net/browse/AXE-7648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): make gas token optional for its and gmp

---

releases/cosmwasm/2025-01-Stellar-GMP-v1.0.0.md

[AXE-7654](https://axelarnetwork.atlassian.net/browse/AXE-7654)
[AXE-7654]: https://axelarnetwork.atlassian.net/browse/AXE-7654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(releases): update stellar GMP deployment commands

---

axelar-chains-config/info/testnet.json
releases/evm/2025-02-XRPL-EVM-GMP-v6.0.4.md

https://axelarnetwork.atlassian.net/browse/AXE-7698

fix: add decimals value for xrpl-evm

---

axelar-chains-config/info/mainnet.json
releases/evm/2025-01-ITS-v2.1.0.md

| task| cmd  | tx |
| ------------- | ------------- | ------------- |
|Migrate ITS Hub contract(v1.1.0) | `./wasm_migrate.sh axelar1aqcj54lzz0rk22gvqgcn8fr5tx4rzwdv5wv5j9dmnacgefvd7wzsy2j2mr 25 '{}'` | [contract migrate tx](https://axelarscan.io/tx/CDD545C8BAFC6334E9160697E77BE3950639AD993F347D42730A0A2D64E71CE4)  |

feat: upgrade ITS  v2.1.0

---

common/utils.js
stellar/README.md
stellar/contract.js
stellar/utils.js

[AXE-7549](https://axelarnetwork.atlassian.net/browse/AXE-7549)
- transfer ownership: https://stellar.expert/explorer/testnet/tx/6169325383733248
- transfer operatorship: https://stellar.expert/explorer/testnet/tx/6170656823590912
[AXE-7549]: https://axelarnetwork.atlassian.net/browse/AXE-7549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): add transfer ownership and operatorship

---

stellar/deploy-contract.js

[AXE-7972](https://axelarnetwork.atlassian.net/browse/AXE-7972)
[AXE-7972]: https://axelarnetwork.atlassian.net/browse/AXE-7972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stellar): modify base options for deploy contract

---

stellar/contract.js
stellar/gateway.js
stellar/operators.js
stellar/utils.js

[AXE-7421](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-7421)
[AXE-7421]: https://axelarnetwork.atlassian.net/browse/AXE-7421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): simulate read-only transactions

---

releases/stellar/2025-01-ITS-v1.0.0.md

[AXE-7987](https://axelarnetwork.atlassian.net/browse/AXE-7987)
[AXE-7987]: https://axelarnetwork.atlassian.net/browse/AXE-7987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(stellar): add gas amount to its release doc

---

stellar/deploy-contract.js

[AXE-8014](https://axelarnetwork.atlassian.net/browse/AXE-8014)
[AXE-8014]: https://axelarnetwork.atlassian.net/browse/AXE-8014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stellar): update example to axelar example

---

axelar-chains-config/info/devnet-amplifier.json
common/utils.js
releases/cosmwasm/2025-01-ITS-v1.1.0.md
releases/stellar/2025-01-GMP-v1.0.0.md
releases/stellar/2025-01-ITS-v1.0.0.md
stellar/README.md
stellar/deploy-contract.js
stellar/gateway.js
stellar/gmp.js
stellar/its.js
stellar/operators.js
stellar/utils.js

[AXE-7547](https://axelarnetwork.atlassian.net/browse/AXE-7547)
[AXE-7547]: https://axelarnetwork.atlassian.net/browse/AXE-7547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): normalize contract name for stellar deployment

---

axelar-chains-config/info/testnet.json
releases/cosmwasm/2025-02-XRPL-EVM-GMP-v6.0.4.md
releases/evm/2025-02-XRPL-EVM-GMP-v6.0.4.md
releases/evm/2025-02-XRPL-EVM-ITS-v2.1.0.md

JIRA: https://axelarnetwork.atlassian.net/browse/AXE-8085

refactor: add deployers and operators for testnet

---

common/utils.js
evm/its.js
stellar/its.js
stellar/utils.js

[AXE-7392](https://axelarnetwork.atlassian.net/browse/AXE-7392)
[AXE-7392]: https://axelarnetwork.atlassian.net/browse/AXE-7392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(interchain-token-service): encode recipient based on chain type

---

common/utils.js
evm/utils.js
stellar/gateway.js
stellar/utils.js
sui/utils/utils.js

[AXE-8187](https://axelarnetwork.atlassian.net/browse/AXE-8187)
[AXE-8187]: https://axelarnetwork.atlassian.net/browse/AXE-8187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: duplicated current verifier set query

---

evm/its.js

Made `its-address` as optional argument in `set-trusted-chains` command.
JIRA: https://axelarnetwork.atlassian.net/browse/AXE-8195

fix: update trusted address command

---

axelar-chains-config/info/testnet.json
common/cli-utils.js
common/utils.js
cosmwasm/README.md
cosmwasm/cli-utils.js
cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js
cosmwasm/utils.js
releases/stellar/2025-01-GMP-v1.0.0.md
releases/stellar/2025-01-ITS-v1.0.0.md
stellar/README.md
stellar/deploy-contract.js
stellar/generate-bindings.js
stellar/utils.js

[AXE-7610](https://axelarnetwork.atlassian.net/browse/AXE-7610)
[AXE-7610]: https://axelarnetwork.atlassian.net/browse/AXE-7610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add new cli option to retrieve tagged contract version or a pre-release commit hash from R2

---

axelar-chains-config/info/testnet.json
releases/stellar/2025-01-GMP-v1.0.0.md

<details>
<summary>Stellar Contracts Deployed</summary>
| Contract        | TX |  CMD | 
| ------------- | ------------- | ------------- |
| `axelar_gateway`  | https://stellar.expert/explorer/testnet/tx/6f9502c78a4ee9ae7299d3ab21da3c81ddfe1a30bd87bb0c2ffb057f532af31b | `node stellar/deploy-contract.js deploy AxelarGateway --version v1.0.0 --minimum-rotation-delay 3600 --previous-signers-retention 15`|
| `axelar_operators`  | https://stellar.expert/explorer/testnet/tx/1dcf9f86d789491bc309afbb1bf410e5ae31f57b07e1826449ef1fec76fdddde | `node stellar/deploy-contract.js deploy AxelarOperators --version v1.0.0`|
| `axelar_gas_service`  | https://stellar.expert/explorer/testnet/tx/86dca8168173ca1554ceb895bfcc9e0b5265a0ea99af9bdd672919e8dd64cfb5 | `node stellar/deploy-contract.js deploy …

chore(stellar): deploy stellar-2025-q1 testnet v1.0.0

---

axelar-chains-config/info/stagenet.json
releases/stellar/2025-01-GMP-v1.0.0.md
releases/stellar/2025-01-ITS-v1.0.0.md

<details>
<summary>Stellar Contracts Deployed</summary>
| Contract        | TX |  CMD | 
| ------------- | ------------- | ------------- |
| `AxelarGateway`  | https://stellar.expert/explorer/testnet/tx/fe42374aa0b111b61adb6685f7c46fe5f8605fdf2a887c07f5401e4c6596a51d | `node stellar/deploy-contract.js deploy AxelarGateway --version v1.0.0 --minimum-rotation-delay 0 --previous-signers-retention 15`|
| `AxelarOperators`  | https://stellar.expert/explorer/testnet/tx/51e60e0765b23a82be78d827bfd9df288285ff29de72a7f2d96e58d9c4898929 | `node stellar/deploy-contract.js deploy AxelarOperators --version v1.0.0`|
| `AxelarGasService`  | https://stellar.expert/explorer/testnet/tx/d6334af721597bad2758463dee94b73617dbcbf8adcfa1cf40e29803a7541e2f | `node stellar/deploy-contract.js deploy …

chore(stellar): deploy stellar-2025-q1 stagenet v1.0.0

---

axelar-chains-config/info/devnet-amplifier.json
releases/stellar/logs/v1.0.0/2025-q1/devnet-amplifier.md
releases/stellar/logs/v1.0.0/2025-q1/mainnet.md
releases/stellar/logs/v1.0.0/2025-q1/stagenet.md
releases/stellar/logs/v1.0.0/2025-q1/testnet.md

Updated the PR description as well:
- https://github.com/axelarnetwork/axelar-contract-deployments/pull/622
- https://github.com/axelarnetwork/axelar-contract-deployments/pull/623
- https://github.com/axelarnetwork/axelar-contract-deployments/pull/621

chore(stellar): update stellar v1.0.0 deployment logs

---

stellar/utils.js

[AXE-8321](https://axelarnetwork.atlassian.net/browse/AXE-8321)
[AXE-8321]: https://axelarnetwork.atlassian.net/browse/AXE-8321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stellar): interchain token service deploy error with artifact path

---

common/its.js
common/utils.js
evm/its.js
releases/stellar/2025-01-ITS-v1.0.0.md
releases/stellar/2025-03-ITS-v1.1.0.md
stellar/README.md
stellar/its.js

[AXE-8357](https://axelarnetwork.atlassian.net/browse/AXE-8357)
```
node common/its.js encode-recipient test CC6FYRUBDJVTATQ55KGPMD2JQFY775BTSJQMRNJEWPEJFUXPOBFSMEOX
destinationChain test not found in config
Human-readable Destination address: CC6FYRUBDJVTATQ55KGPMD2JQFY775BTSJQMRNJEWPEJFUXPOBFSMEOX
Encoded ITS destination address: CC6FYRUBDJVTATQ55KGPMD2JQFY775BTSJQMRNJEWPEJFUXPOBFSMEOX
```
```
node common/its.js encode-recipient stellar-2025-q1 CC6FYRUBDJVTATQ55KGPMD2JQFY775BTSJQMRNJEWPEJFUXPOBFSMEOX
Human-readable Destination address: CC6FYRUBDJVTATQ55KGPMD2JQFY775BTSJQMRNJEWPEJFUXPOBFSMEOX
Encoded ITS destination address: 0x4343364659525542444a565441545135354b47504d44324a5146593737354254534a514d524e4a455750454a465558504f4246534d454f58
```
[AXE-8357]: …

chore(stellar): use encoded its destination and remove unused encode recipient

---

axelar-chains-config/info/testnet.json
releases/xrpl/2025-02-v1.0.0.md

https://axelarnetwork.atlassian.net/browse/AXE-8535

feat: add decimals in xrpl chain

---

releases/ampd/2025-04-03-ampd-v1.6.0.md

there was an error in the testnet config for ampd 1.6.0

fix: update testnet config for ampd 1.6.0

---

releases/cosmwasm/2025-02-XRPL-EVM-GMP-v6.0.4.md
releases/evm/2025-02-XRPL-EVM-GMP-v6.0.4.md

- add correct deployer address and deployment method for XRPL EVM GMP stagenet

chore: xrpl evm release docs correction

---

releases/cosmwasm/2025-05-XRPL-v1.2.0.md

Migrate XRPLGateway, XRPLMultisigProver, & XRPLVotingVerifier from `v1.1.2` to `v1.2.0`

docs(release): migrate to XRPL v1.2.0

---

axelar-chains-config/info/devnet-amplifier.json
axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json
releases/stellar/2025-05-ITS-v1.2.0.md
releases/stellar/logs/v1.2.0/2025-q1/2025-05-ITS-v1.2.0-devnet-amplifier.md
releases/stellar/logs/v1.2.0/2025-q1/2025-05-ITS-v1.2.0-stagenet.md
releases/stellar/logs/v1.2.0/2025-q1/2025-05-ITS-v1.2.0-testnet.md

[AXE-9348](https://axelarnetwork.atlassian.net/browse/AXE-9348)
[AXE-9348]: https://axelarnetwork.atlassian.net/browse/AXE-9348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(stellar): stellar ITS v1.2.0 deployment

---

axelar-chains-config/info/mainnet.json
releases/evm/2025-05-Plume-ITS-v2.1.0.md

- update approx time to finality in mainnet config
- update ITS release doc

chore: update plume config and release docs

---

releases/cosmwasm/2025-06-XRPLMultisigProver-v1.4.2.md

Migrate `XRPLMultisigProver` from v1.4.1 to v1.4.2

docs(release): migrate to XRPLMultisigProver v1.4.2

---

stellar/token-utils.js

rename `deploy_stellar_asset_contract` to `create_stellar_asset_contract`

chore(stellar): update stellar token utils function name

---

releases/stellar/2025-06-TokenUtils-v1.0.0.md

[AXE-9722](https://axelarnetwork.atlassian.net/browse/AXE-9722)
[AXE-9722]: https://axelarnetwork.atlassian.net/browse/AXE-9722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(release): stellar token utils release doc

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json
releases/stellar/2025-06-TokenUtils-v1.0.0.md

[AXE-9722](https://axelarnetwork.atlassian.net/browse/AXE-9722)
[AXE-9722]: https://axelarnetwork.atlassian.net/browse/AXE-9722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(stellar): token utils v1.0.0 config update

---

.github/workflows/generate-config.yaml

- fix networks list parsing to loop through the networks names

fix: parse network list correctly

---

cosmwasm/utils.js
releases/cosmwasm/2025-07-ITS-v1.3.0.md

TODO: add support for actually deploying the its-abi-translator contract to the deployment scripts

chore(releases): add ITS 1.3.0 release doc

---

package-lock.json
package.json
stellar/utils.ts

[AXE-9812](https://axelarnetwork.atlassian.net/browse/AXE-9812)
[AXE-9812]: https://axelarnetwork.atlassian.net/browse/AXE-9812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): protocol v23 update on deployment script

---

.github/workflows/generate-config.yaml
.github/workflows/reusable-update-config.yaml
axelar-chains-config/info/devnet-amplifier.json
axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json

This reverts commit 3d1d5732e94d5482238338fafb301b0885a20fdd.

test: revert config test update

---

axelar-chains-config/info/stagenet.json
releases/stellar/2025-08-GMP-v1.1.1.md
releases/stellar/2025-08-ITS-1.2.0.md

CLI output: https://app.warp.dev/drive/notebook/Output-kMTlNHh4HvJXtNHl6QWHRe

chore: deploy stellar 2025 q3 stagenet

---

axelar-chains-config/info/devnet-amplifier.json

[AXE-9645](https://axelarnetwork.atlassian.net/browse/AXE-9645)
[AXE-9645]: https://axelarnetwork.atlassian.net/browse/AXE-9645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(stellar): cleanup deprecated stellar configs

---

cosmwasm/README.md
cosmwasm/query.js
cosmwasm/submit-proposal.js
cosmwasm/utils.js

- add --update option to its-hub-register-chains commands
- update csomwasm README

feat: add option to update chain registration on its hub
