evm/deploy-const-address-deployer.js
evm/deploy-contract.js
evm/deploy-create3-deployer.js
evm/deploy-gateway-v4.3.x.js
evm/deploy-gateway-v5.x.js
evm/index.js
evm/utils.js

- Allow regular `http` get request
- import `ConstAddressDeployer` and `ConstCreate3Deployer` from `axelar-network/axelar-gmp-sdk-solidity` repo
- use correct function name for deploying contract at `evm/deploy-const-address-deployer.js`
- check that governance chain address is a string, but not an EVM address
- ran linter and prettier

fix(scripts): miscellaneous corrections

---

evm/deploy-const-address-deployer.js

Update json configuration with `ConstAddressDeployer` address and deployer even when exiting earlier due to already being deployed

fix(config): update `ConstAddressDeployer` address and deployer

---

evm/deploy-upgradable.js
evm/upgradable.js
evm/utils.js

PR for deployment script to log an error if gas service or deposit service is deployed using create3.

fix: add checks for contracts incompatible with create3

---

evm/deploy-contract.js

Tested from my local with the following steps:
1. Clone `git clone git@github.com:axelarnetwork/interchain-governance-executor.git`
2. Install dep `yarn` 
3. Compile contracts `yarn compile`
1. Added my private key in `.env`
2. Execute a command and provide a path to the contract 
```
node evm/deploy-contract.js -n fantom -a ../../interchain-governance-executor/artifacts/contracts/ -c InterchainProposalSender -m create2
```

feat: added InterchainProposalSender constructor args

---

evm/deploy-gateway-v5.0.x.js
evm/utils.js

Adjust amplifier contract query to new key rotation logic. Key ID is not longer needed to get current worker set
https://axelarnetwork.atlassian.net/browse/AXE-1683

feat: update amp worker set query to not use keyID

---

axelar-chains-config/src/utils/verifyContract.js

[AXE-2349]
[AXE-2349]: https://axelarnetwork.atlassian.net/browse/AXE-2349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: make verify synchronous

---

evm/broadcast-transactions.js
evm/deploy-contract.js
evm/governance.js
evm/utils.js

[AXE-2405]
[AXE-2405]: https://axelarnetwork.atlassian.net/browse/AXE-2405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: identify chain from signed tx during broadcast

---

evm/deploy-its.js

This avoids the scenario where two chains are added under the same (for e..g a new ethereum testnet since old is deprecated)

fix: use chain id for unique chain naming

---

.github/workflows/test.yaml
evm/balances.js
evm/broadcast-transactions.js
evm/check-wallet-balance.js
evm/cli-utils.js
evm/deploy-const-address-deployer.js
evm/deploy-contract.js
evm/deploy-create3-deployer.js
evm/deploy-gateway-v4.3.x.js
evm/deploy-gateway-v6.2.x.js
evm/deploy-its.js
evm/deploy-upgradable.js
evm/execute-contract.js
evm/gateway.js
evm/governance.js
evm/min-deposit-proposal.js
evm/multisig.js
evm/operators.js
evm/ownership.js
evm/remove-info.js
evm/send-tokens.js
evm/update-nonces.js
evm/update-static-gas-options.js
evm/utils.js
evm/verify-contract.js

Remove duplications in deployment scripts as per [AXE-2432](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2432)
[AXE-2432]: https://axelarnetwork.atlassian.net/browse/AXE-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: script optimizations

---

evm/deploy-contract.js
evm/deploy-gateway-v6.2.x.js
evm/gateway.js
evm/utils.js

- Also add improved colouring options

fix: improve gateway script to transfer permissions

---

axelar-chains-config/info/mainnet.json
evm/deploy-const-address-deployer.js
evm/deploy-contract.js
evm/deploy-create3-deployer.js
evm/deploy-gateway-v4.3.x.js
evm/deploy-gateway-v6.2.x.js
evm/deploy-its.js
evm/deploy-upgradable.js
evm/gateway.js
evm/governance.js
evm/interchainTokenFactory.js
evm/its.js
evm/multisig.js
evm/operators.js
evm/ownership.js
evm/send-tokens.js
evm/utils.js

Added gas adjustment option and `getGasOptions` method as per [AXE-2572](https://axelarnetwork.atlassian.net/browse/AXE-2572)
Note: There was a discrepancy in `gasPriceAdjustment` for mainnet Fantom, Binance, and Polygon between `1.6` and `1.4` in the gateway deployment vs governance scripts. I stuck with the higher value in the chain configs.
[AXE-2572]: https://axelarnetwork.atlassian.net/browse/AXE-2572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add gas adjustment option

---

.github/workflows/test.yaml
evm/utils.js

Small fix for `getGasOptions`, the recent addition of the `defaultGasOptions` optional parameter and lack of correct parentheses surrounding two ternary expressions was causing `gasOptions` to be returned as `undefined` as opposed to `{}` which was causing the `copyObject` method to throw an error. I added `gasOptions` in both the chain config and contract config for the GitHub action test to detect similar errors earlier.

fix: get gas options

---

axelar-chains-config/tests/schema/index.js
cosmwasm/deploy-contract.js
evm/its.js
evm/utils.js

Remove lingering instances of `chain.id` to `chain.axelarId`

fix: remove remaining instances of id

---

axelar-chains-config/info/testnet.json

- Remove Eth goerli testnet as it's deprecated and move eth sepolia to the top of the configs

chore: remove eth goerli testnet

---

evm/sign-message.js

Add `require('dotenv').config();` to be able to use env in script.

chore: read env variables

---

sui/README.md

chore: improve sui readme

---

cosmwasm/deploy-contract.js

The amplifier Multisig contract now requires and `admin_address` field and a new way to encode the `blockExpiry` field. This PR updates the deployment script accordingly

chore(cosmwasm): update Multisig instantiation message

---

sui/README.md
sui/amount-utils.js
sui/cli-utils.js
sui/gas-service.js
sui/types-utils.js
sui/utils.js

[AXE-4393](https://axelarnetwork.atlassian.net/browse/AXE-4393)
[AXE-4393]: https://axelarnetwork.atlassian.net/browse/AXE-4393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add gas service commands

---

stellar/deploy-contract.js

[AXE-4342]
[AXE-4342]: https://axelarnetwork.atlassian.net/browse/AXE-4342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stellar): u128 signature weight

---

package-lock.json
package.json
sui/deploy-contract.js
sui/deploy-gateway.js
sui/deploy-test.js
sui/deploy-utils.js
sui/faucet.js
sui/gas-service.js
sui/gateway.js
sui/multisig.js
sui/sign-utils.js
sui/transfer-object.js
sui/types-utils.js

- Bumped `@axelar-network/axelar-cgp-sui` to `0.3.0`
- Removed `@mysten/sui.js`
- Added `@mysten/sui@1.3.0`
- Fixed all incompatible issues with new sui sdk
- Fixed gateway deployment script due to [the update](https://github.com/axelarnetwork/axelar-cgp-sui/pull/76) in gateway contract's function signature

chore: use axelar-cgp-sui 0.3.0 and sui sdk 1.x

---

cosmwasm/README.md
cosmwasm/submit-proposal.js
cosmwasm/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-4442

feat(amplifier): allow to automatically fetch the code id from the network when submitting an instantiation proposal

---

cosmwasm/README.md
cosmwasm/submit-proposal.js
cosmwasm/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-4460

feat(amplifier): support for execute message through governance

---

cosmwasm/README.md
cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js
cosmwasm/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-4502

feat(amplifier): add proposal type storeInstantiate

---

common/utils.js
sui/README.md
sui/deploy-contract.js

address remaining comments in https://github.com/axelarnetwork/axelar-contract-deployments/pull/323

chore: cleanup deploy script pr

---

cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js
cosmwasm/utils.js

adds option `-l, --label` to specify custom label for contract instances
https://axelarnetwork.atlassian.net/browse/AXE-4645

feat(amplifier): allow custom instance labels

---

axelar-chains-config/info/stagenet.json

Notes:
* This is needed to test deposit service in stagenet - doesn't look like this has been deployed since the refresh
* Needed this asap so deployed myself - hopefully I didn't do it wrong
* I checked which wrapped assets are registered for the active EVM chains first - `wavax-wei`, `wdev-wei`, and `wftm-wei` are registered and confirmed everywhere, no other wrapped tokens are, hence only having those three deployed in this PR
* For lack of any better ideas, I took `refundIssuer` from old stagenet [here](https://github.com/axelarnetwork/axelar-contract-deployments/blob/fedbfeed03ac4618b1de769191612cc91abef0a1/axelar-chains-config/info/stagenet.json#L34)
Deployed using the stagenet deployer wallet like so:
```
node evm/deploy-upgradable.js -e stagenet -n avalanche -c …
```

chore: partially deploy deposit service in stagenet

---

common/cli-utils.js
evm/cli-utils.js
evm/deploy-amplifier-gateway.js
evm/deploy-contract.js
evm/deploy-gateway-v6.2.x.js
evm/deploy-its.js
evm/deploy-upgradable.js
evm/interchainTokenFactory.js
evm/its.js

This PR moves `addExtendedOptions` function to `evm/cli-utils.js` since it's more closelyrelated to the evm scripts.

chore: move addExtendedOptions to evm/cli-utils

---

.github/workflows/test-sui.yaml
sui/faucet.js
sui/multisig.js

This PR added the `init` command to `multisig.js`, in order to make [the multisig flow](https://github.com/axelarnetwork/axelar-contract-deployments/pull/339#discussion_r1733924184) smoother.
The init command receives the following params from the cli options: 
- `base64PublicKeys`
- `threshold`
- `schemaTypes`
- `weights` 
Then, it constructs the `multisig` object save into the config file.

feat(sui): add init multisig command

---

cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js
cosmwasm/utils.js

https://axelarnetwork.atlassian.net/browse/AXE-4714

refactor(amplifier): update to async style

---

common/utils.js
cosmwasm/cli-utils.js
cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js
cosmwasm/utils.js

Amplifier scripts breaking changes:
- comma separated chains in `chainNames` (e.g. `-n chain1,chain2`) no longer supported, now the caller must execute the script once per chain
- `none` is no longer supported as a valid value for `chainNames` to denote no chain is required
https://axelarnetwork.atlassian.net/browse/AXE-5188

feat(amplifier)!: remove support for looping through multiple chains

---

.github/workflows/test-sui.yaml

Thanks @milapsheth  for working on [this](https://github.com/axelarnetwork/axelar-contract-deployments/pulls?q=is%3Apr+is%3Aclosed). This PR removes the `continue-on-error` which recently added to ignore the gateway call-contract issue.

chore: remove continue-on-error since the issue is resolved

---

package-lock.json
package.json
stellar/README.md
stellar/deploy-contract.js
stellar/operators.js
stellar/utils.js

closes https://axelarnetwork.atlassian.net/browse/AXE-6664 
supersedes #439 
Stop using the `stellar` command to deploy contracts and instead rely on the JS sdk. To do so, needed to upgrade the stellar sdk version to `13.0` to support protocol v22 (where constructors are introduced).
- Mostly based on the [stellar doc](https://developers.stellar.org/docs/build/guides/transactions/install-deploy-contract-with-code) which describes the process.
- Also reworks the `upgrade` command to use the SDK.
- `SorobanRpc` was removed in 13.0, renamed to `rpc`
- `--initialize` has been dropped since all contracts are initialized when constructed now.
- `broadcast` now returns the full response instead of just `the .value()`, since the full response is needed to extract the contract address. 
- This …

feat(stellar): upgrade to stellar-sdk v13.0 and support constructor initialization

---

sui/its.js

https://axelarnetwork.atlassian.net/browse/AXE-6784
This PR allows multiple target chains for `setup-trusted-address` command with the comma-separated chains. It also supports a special tag e.g. `all-evm` to target all evm chains that has `InterchainTokenService` deployed.

feat(sui): support multiple trusted addresses

---

axelar-chains-config/info/devnet-amplifier.json
sui/README.md
sui/its.js

https://axelarnetwork.atlassian.net/browse/AXE-6783
```
node sui/its.js remove-trusted-address chain1,chain2,...
```

feat(sui): add command to remove trusted address on sui

---

cosmwasm/cli-utils.js
cosmwasm/submit-proposal.js
cosmwasm/utils.js

When submitting a proposal to store code, it will check if the contract has been previously deployed, if yes then it will add the contract admin and creator by default to the list of addresses allowed to instantiate. This is done to prevent issues like blocking migration if the admin address has no instantiation rights
https://axelarnetwork.atlassian.net/browse/AXE-6727

feat(cosmwasm): add previous admin and creator by default to instantiation permissions

---

stellar/utils.js

[AXE-7061](https://axelarnetwork.atlassian.net/browse/AXE-7061)
- rotate signers with amplifier verifiers were failing with [ContractError::InvalidSigners](https://github.com/axelarnetwork/axelar-cgp-soroban/blob/778ee8eea30b9feb73aacf922fc3c5fe32cd068d/contracts/axelar-gateway/src/auth.rs#L223) and this is because of the incorrect order of signers.
```
Error: HostError: Error(Contract, #4)
Event log (newest first):
0: [Diagnostic Event] contract:CBECMRORSIPG4XG4CNZILCH233OXYMLCY4GL3GIO4SURSHTKHDAPEOVM, topics:[error, Error(Contract, #4)], data:"escalating Ok(ScErrorType::Contract) frame-exit to Err"
1: [Diagnostic Event] topics:[fn_call, CBECMRORSIPG4XG4CNZILCH233OXYMLCY4GL3GIO4SURSHTKHDAPEOVM, rotate_signers], data:[{nonce: Bytes(0000000000000000000000000000000000000000000000000000000000 …
```

fix(stellar): update sorting for rotate signers with amplifier verifiers

---

cosmwasm/README.md
cosmwasm/deploy-contract.js
cosmwasm/submit-proposal.js
cosmwasm/utils.js

Available subcommands:
- `upload`: Uploads wasm file and saves codeId to `lastUploadedCodeId` in config
e.g.: `node cosmwasm/deploy-contract.js upload -m "$MNEMONIC" -a "../artifacts/" -c "Router" --instantiate2 -e devnet -y --salt "$ROUTER_SALT"`
- `instantiate`: Instantiates a contract, it gets the codeId by order of priority from:
1. Value of `--codeId` option
2. From the network by comparing code hash when using `--fetchCodeId` option
3. Value of previously saved `lastUploadedCodeId` in config
e.g.: `node cosmwasm/deploy-contract.js instantiate -m "$MNEMONIC" -c "Router" --instantiate2 -e devnet --admin "$ADMIN_ADDR" -y --salt "$ROUTER_SALT"`
- `upload-instantiate`: Both uploads and then instantiates a contract using the code Id that was just created. It doesn't accept `--codeId` nor …

feat(cosmwasm)!: change non-governance scripts to use subcommands

---

axelar-chains-config/info/devnet-amplifier.json
axelar-chains-config/info/mainnet.json
axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json

https://axelarnetwork.atlassian.net/browse/AXE-7116

refactor: add config params to stellar network for finality

---

.github/workflows/test-evm.yaml
evm/interchainTokenFactory.js
evm/its.js
evm/utils.js
package-lock.json
package.json

[AXE-7089]
[AXE-7089]: https://axelarnetwork.atlassian.net/browse/AXE-7089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(evm)!: support ITS v2.1 release

---

stellar/README.md
stellar/utils.js

[AXE-7250](https://axelarnetwork.atlassian.net/browse/AXE-7250)
[AXE-7250]: https://axelarnetwork.atlassian.net/browse/AXE-7250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(stellar): update readme and stellar cmd

---

sui/utils/sign-utils.js

https://axelarnetwork.atlassian.net/browse/AXE-7288
Add try-catch block around `decodeSuiPrivateKey` to avoid exposing sensitive data

chore(sui): avoid printing private key

---

sui/README.md
sui/deploy-contract.js
sui/utils/sign-utils.js
sui/utils/upgrade-utils.js

https://axelarnetwork.atlassian.net/browse/AXE-7481
This PR introduces the `immutable` deployment policy option, which allows packages to be permanently locked from future upgrades. When this policy is provided, the `UpgradeCap` is automatically discarded after the package is published, making the package immutable and preventing any subsequent upgrades.
- Allow passing `immutable` policy for the `node sui/deploy-contract.js deploy` command
- Apply upgrade policy after all packages deployment, instead of just `Gateway` contract. This only applies when the policy option is specified and it is not `any_upgrade` policy.
- Update `sui/README.md` for this changes.
- Bonus: Removed duplicated package deployment log.
- Bonus: Add action name to the tx confirmation prompt
1. Add …

refactor(sui): update upgrade policy handling and add immutable policy

---

sui/deploy-contract.js

[AXE-7512]
[AXE-7512]: https://axelarnetwork.atlassian.net/browse/AXE-7512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sui)!: track more objects on deployment

---

axelar-chains-config/info/stagenet.json
evm/its.js
releases/cosmwasm/2025-01-ITS-v1.1.0.md
releases/evm/2025-01-ITS-v2.1.0.md

Upgrade ITS hub -> v1.1.0
| task| cmd  | tx |
| ------------- | ------------- | ------------- |
|Upload new ITS Hub contract(v1.1.0) | `node cosmwasm/submit-proposal.js store -c InterchainTokenService -t "Upload InterchainTokenService contract v1.1.0" -d "Upload InterchainTokenService contract v1.1.0" -r axelar10d07y265gmmuvt4z0w9aw880jnsr700j7v9daj --deposit 2000000000 --instantiateAddresses axelar1pumrull7z8y5kc9q4azfrmcaxd8w0779kg6anm,axelar10d07y265gmmuvt4z0w9aw880jnsr700j7v9daj,axelar12qvsvse32cjyw60ztysd3v655aj5urqeup82ky -a ./wasm` | [proposal tx](https://stagenet.axelarscan.io/proposal/102) |
|Migrate ITS Hub contract(v1.1.0) | `./wasm_migrate.sh axelar1ph8qufmsh556e40uk0ceaufc06nwhnw0ksgdqqk6ldszxchh8llq8x52dk 29 '{}'` | [contract migrate …

chore: its hub v1.1.0 

---

stellar/deploy-contract.js
stellar/gateway.js
stellar/its.js
stellar/operators.js
stellar/utils.js

[AXE-7488](https://axelarnetwork.atlassian.net/browse/AXE-7488)
- `is_operator`, `add_operator`, `remove_operator` functions has been tested.
- `collect_fees`: https://stellar.expert/explorer/testnet/tx/4562552348495872
```
node stellar/operators.js collect_fees CCQSKSL4FSHQT6OF5BS7KHHDUTFSC36BWQH55NFUHWRMMNCRWVRP5GEL --gas-fee-amount 1
```
- `refund`: https://stellar.expert/explorer/testnet/tx/4562612478029824
```
node stellar/operators.js refund 0x04593938310ffac16d1d7f11c55cadc1200af00e68ded8b5465558d481685a84-276 CCQSKSL4FSHQT6OF5BS7KHHDUTFSC36BWQH55NFUHWRMMNCRWVRP5GEL```
```
[AXE-7488]: https://axelarnetwork.atlassian.net/browse/AXE-7488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(stellar): refactor operators script and add missing commands

---

package-lock.json
package.json
sui/its-example.js

https://axelarnetwork.atlassian.net/browse/AXE-7769
Update `axelar-cgp-sui` to `1.1.3` and include sui token deployment with `mint_and_burn` mode in the example
- Our current Example contract on `devnet-amplifier` haven't support `mint_and_burn` mode yet because we need to deploy a new contract first. cc: @blockchainguyy

chore: update its example and axelar-cgp-sui

---

package-lock.json
package.json

This PR remove caret from xrpl dependency.
JIRA: https://axelarnetwork.atlassian.net/browse/AXE-9142

fix: remove caret from xrpl dependency

---

evm/README.md
evm/cli-utils.js
evm/top-up.js
evm/utils.js

This is useful when performing stress tests, so that multiple accounts can be funded before the load test script is executed to generate transactions in parallel from these accounts
https://axelarnetwork.atlassian.net/browse/AXE-9496

feat: add script to top up multiple EVM accounts from a single wallet

---

common/utils.js

Correctly encode `xrpl` destination address for evm to xrpl its
```sh
node evm/its.js interchain-transfer -n xrpl-evm xrpl 0xb...4f r9...uN 1 --gasValue 100000000000000000
```

fix(xrpl): encoding of xrpl address for its

---

axelar-chains-config/info/mainnet.json
axelar-chains-config/info/stagenet.json
axelar-chains-config/info/testnet.json

Publicnode's Sui RPC has been unstable lately. Sometimes it's just slow to respond, other times it's returning http 500 errors.
This PR migrates Sui RPC from [Publicnode](https://sui-rpc.publicnode.com/) to [Blastapi](https://blastapi.io/public-api/sui). 
After one day of tests, Blastapi has so far remained stable and seems generally faster.

chore: migrate sui rpc node from publicnode to blastapi

---

cosmwasm/utils.js

This PR adds the coordinator's address to the multisig contract's instantiate message. Please see https://github.com/axelarnetwork/axelar-amplifier/pull/953 for reference

fix(cosmwasm): add coordinator to multisig instantiation message

---

axelar-chains-config/info/devnet-amplifier.json
releases/cosmwasm/2025-07-Solana-GMP-DRAFT.md
releases/solana/2025-07-GMP-v1.0.0.md
releases/solana/2025-07-ITS-v1.0.0.md
solana/Cargo.lock
solana/Cargo.toml
solana/src/gas_service.rs
solana/src/gateway.rs
solana/src/governance.rs
solana/src/its.rs
solana/src/main.rs
solana/src/memo.rs
solana/src/utils.rs

Several changes were required to the scripts and some instructions as well, here's the rationale:
- There was a recent change done earlier related to the chain id (because it can be `solana-2` for instance and not always `solana`). It's changed to be taken as input and not inferred anymore, but it wasn't updated properly in all places where we were using it to index the json file. Thus I had to fix it during the deployment.
- The gas service program used to take an "authority", the terminology was recently updated in the contract to "operator", thus I updated here to be consistent.
- We were calculating the domain separator in the scripts for gateway initialization, but because of the issue we had where the `MultisigProver` was instantiated with the domain separator calculated with …

chore(solana): devnet deployment
